---
apiVersion: v2
appVersion: "1.0"
dependencies:
  - name: rikami
    repository: oci://ghcr.io/b-zago/rikami-charts
    version: 0.1.1
description: Scorevaulting test app
name: scorevaulting
type: application
version: 0.1.0
