env: staging
---
deployments:
  - component: cache
    containerPort: 6379
    image: redis:8-alpine
    name: redis
    runsOn: redis
  - component: database
    envSecretRef: database-envs
    image: postgres:18-alpine
    name: database
    runsOn: postgres
secrets:
  - data:
      SOME_SECRET1: AgABYBxDs6a3NXUu1uwmuzCdjbY10ZvjGFCfKy/AXgXrvGZt4J2VMWVaeILDEM/vc3B2CDXvT8R76Zl8giFRld97glgcGz5TCvo7V8kaJn+qC1+YeVBBIKnBf4Nf1qroUdetRpliYfrPn6nTy0QQuOGpkEaR6Ct+buMbFjazxCR9SPMQ7BzXMDsSf1ns0VTRA/WmrDJjUTSgZQVF5OUVx6KvER3vlHibtpP9Crl9gFOsLl1D7iTdgGobfubLlzW5oKWWSGWd286kGL4o0tVb67YzgjjmlOPvPa3YwvsNCLQi+C51KZMO2R0s/e/8I40qVCsYjSNwRKQ6OTJqdgFhvjQNpQgKytFFylbHMV8HNzFqiLH/k1LSysIKYuIozi1e0oTMQsxL/jkM6OHj8YuoXDhLMJVZTbdJcqX3p6qJtXPeMWw7cs7unpXo+mJiQtMyoNci/h42r6nCxGFQf26RuwQg2EsM3BCgLFNLzq8v3vvprTWFAvcmTVVQi0vTWqw0mvTGKq5w2+d0cz6fkQhxQyIzZ1GTtafhQeFTEA6zLQUTUbfONexgQZH+B9w+Bn9ubgvAosdXBEg7E3E3gdoIkbPZAq2+jD4+kkSPR5WjlTIOn8k5vKHlkP7s2L3a9BVbnzMSbQpUBg53Lg8mj4VBhq9jMV4WGUaIGlGas6Pt9wXlz6j7z7ZIthj9Ufr0Hg11kHxLpHE6MALNh/AM
      SOME_SECRET2: AgB3qiZeO+B4ALrDrNw0N5fvB9iYGo//GpEzhVjk6iwL3Wl4j5Q6rKT9ZfGssbUplpO3D2+iXn+9DzarHGalmJw8o07lKbdyAvnGS5mRlfV7pLFIkiR2Z4EfPSiYij5ltEsScxs1PAnO5Nl3EewDMBPKXJ2JAIZuY2U0V6ipahXz4KH0m46CTG/Z9xGIXjMKS3nS00NkWq0v46LdKlCSVkQOFC92vyQMrxHAJcnglaTBt3C5Cq8WN1ZlLZZDLN1WUgVy1KYxh3kk4hzehB34f0SdyX8VUWppD66tC6CASKrVbx8rXhBBOPhrqGlHerOTuAnwjW3fJInXFCsxUyjufSVc5kwV0GzdVnp68uihxq8jNY6gtVxv7HEzLn5z7qjm4IG5ADH0fSwYdT4im4PDHby9yFOKM32ILD+ATohVLJ2T7mDRl9dCXvPYeiRB2u+zGhUEcVHpsrNaed6I8vzJjQNJ5+Xo+polOtrCYNu3MLXlbZFFiUkVyxjFJwVVbD9Ivjf7+20Ybbtc37lkm90Hcho8PjJE4aot+PBfsBngtI5GumC/BhKCRob5FQ4vU77xQpBTLQRDFc1ziAPO76CE8wWU1FVJaz2PmhJWw2y7G9IdvoU2PLk4iy9Gzt7DfkzByJ3BT8cREOwSUpObbVg4c2utdv2L3UiuXKJKjwu0PgSg5P+ioHmEfaQIf+vf9Pw0EHfaNQh8PfgPrQ==
    listTargetTest: otherval
    listTraversal:
      - t4val
    name: database-envs
    runsOnList:
      - database
services:
  - name: redis-service
    port: 6379
    runsOn: redis
    targetPort: 6379
  - list:
      - someval1
      - otherval
    list2:
      - t1: t1val
        t2: t2val
      - t3: t3val
        t4: t4val
    name: database-service
    port: 5432
    runsOn: database
    targetPort: 5432
