env: staging
---
deployments:
  - component: cache
    containerPort: 6379
    image: redis:8-alpine
    name: redis
    runsOn: redis
  - component: database
    containerPort: 5432
    envSecretRefs:
      - database-envs
    image: postgres:18-alpine
    name: database
    runsOn: postgres
  - component: server
    containerPort: 8000
    envSecretRefs:
      - database-envs
    envVars:
      - name: DB_HOST
        value: scorevaulting-database-service
      - name: REDIS
        value: scorevaulting-redis-service
    image: ghcr.io/b-zago/scorevault/webserver:latest
    imagePullSecret: ghcr-creds
    name: web-server
    runsOn: python
routes:
  - host: scorevaultin.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
secrets:
  - data:
      SOME_SECRET1: AgAJ7P1+3CJ178ZR3LD8J77E/5CQr8EH5EIgWI7cKEJBXOcExdiIC0bgAa4zqnTtHn+rjTd2S6VtYD4fYoCIRojQCwQx34EReCK8fOKOAoSjHvuihmmliCpnF2KWvdjfsFA+vu/eNjyt2zN50C8bdpk0EvpZyCUFcFdUvs/LG6ymYrxsAjVUxHzMCNxgFO11rxtIMA6v+HT5pwxmbjNKXO08ha9Tzu3ZRy5+BmY/88c3JdgnmXgrMeU55EzebtIX7snpvAliLxfTPPYBOXly+dYIbBuwr/NGHr1/FCVIjJx5ztRI6mzhNXVJif9q0BmRvhOAxJu/4E6Ra5vTtCUVskfSvuPOfUvgqaWBUOSDzkQ8a5Qr1oB5jTBfxXx4fOznzuLyNSrVqms2ofXQ0TJdF36xi22ECCTUtpeqH+QWglpzkIJvKfHxvwN5sOQc4d8p6tFvdk+30AM9LGj0Oof3wYCyuq2TPWuUNOsW5L5PiQ4HaxzKDRR408xLi00InH/O3xYM/WcxPzSNyWM0ewBPyMG/hg/MIBhQsjtcy1EaAK8f8nHTe0E+XVY6M264E6TrpXi0xHDwnPO6dS+dPqOmIQUs4nXnRHeUEgkhlPwUTLyTggwHIUDF5R2dJre1R4mHv8r0b5vtu8abUT81Yah1ihbnWWkNgsMQt/KTdc6V8+CXPfk8OkBVZvf85yCdjVa1daXROSqitsJ5cmgX
      SOME_SECRET2: AgCf/oIKP57bYcAV+ThAgVAC9MAehOPDu0cB3ls7SduxZ1UJYRKb+dROJRrgXWkGsMtq7OT5SoS4jONpEGbeD3rhU2hiHUB03chipFyE14x5m89kLTmDHTvVJt5sQ9lmFkZyxUZNjBcMXj5kz1Gg3OeGxuHo8ZN5YOk1jhuuefauDiVwKxTICzDATFvr3UIyI3ATdzf6Q9YHXPJMhSR2wAWtw0oeJ5i9QmAxeG2aGgeGjvoLcPqNzcCRwi6mfI9NbeL+rz0KXfHhDjatA+japv+T3dXY7xVk4FlrOfZajTSe0WZcBP1RCYK0uNvItPd7RELznCyWSC2Nt6Q7ds85aA1XFDdmNP8bcVgvT7IdoR47SGwd+kK7SstbTBsIbQuvBnn2xpkHwcf3h4T/sBGGNuM/Qqgbz5K8YvrSOAP9dW3q72ci3DVWSQ4ZF0778rPdlP/pLLEoBHH9iueePfMpI9CysaYMb+HjaeVHNlR5FrmIx6Q+l41Qq6UgwqYPbvpvmAOgc1Luz5yI0es0TjKN7FLprLscfsBWDiVRvs1JIB24PPK4PIk0VjxbIgROAy7Wao92hxcWYTuprGIqatMglNVcr5MTcROLe6anrhsc+XRS5jD1swggrh/wpTTDY0mKlOdPYKScRA7oH6w91z/ENCQOQSivPhMXWFR29nXR5Zc13ueJPcHn6wVqvMW0JMV9bL/qwNoiyfxqKA==
    name: database-envs
    runsOnList:
      - database
services:
  - name: redis-service
    port: 6379
    runsOn: redis
    targetPort: 6379
  - name: database-service
    port: 5432
    runsOn: database
    targetPort: 5432
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 8000
