env: prod
---
deployments:
  - component: cache
    containerPort: 6379
    image: redis:8-alpine
    name: redis
    runsOn: redis
  - component: database
    containerPort: 5432
    envSecretRefs:
      - database-envs
    image: postgres:18-alpine
    name: database
    runsOn: postgres
  - component: server
    containerPort: 8000
    envSecretRefs:
      - database-envs
    envVars:
      - name: DB_HOST
        value: scoredvauld-database-service
      - name: REDIS
        value: scoredvauld-redis-service
    image: ghcr.io/b-zago/scorevault/webserver:latest
    imagePullSecret: ghcr-creds
    name: web-server
    runsOn: python
routes:
  - host: scorevaultin.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
secrets:
  - data:
      SOME_SECRET1: AgBMeQviUSM2hClRTRwKWoo0iEEAFKePD6CJOVr/QkjsB6ltV/VJad4ijBC0i0ZtuTOa35aq+g/1/zyUZ86+UuhSTvr9Hb2zMO28lGA2MnLgAi25HWGiS1Pf7FvfOq5UnfRo61ELGTQldteJ35AFsoe6N6F64oMJTefbPSEDmLp96ew+3XtJZ3G2whEsoQSsc3QFJm293CCnbqt1hqe/nwB+U/AluHoxGIZdlEE7NiJtbfbTh81H0W7wxmyYxnYKsO9kNZC2Fn8+uTtxvPyJwtJwTpftLAcG47fhEKWCcXCNbAu97vFONRXSDRz1StITCsh12wViE3FOm+OQatpGTG9xk6grEHc1oE5R9Z1++R3shJcv3YLDUzMBfRqzYC33Yz9hdpCeIGhlqxMabz+BTmpvjfATn+B4+vqwzy5DuJuNj3/x1Mx74UkKgTWvuF2SCioB7XepEdjpRcbct29zMMZbijFuWkyhMCaEJW9PqvdTjGuN086zfMIWX23Ok+xbkxBQ5t5v5PmMnoGULYhQUXEYBFA9yViAWIH0xP0HTyKBCzn+x2zUwguTBVhDycCY13SQxwRs5d7DOJ5FlP5pSanhKrG7EgZKFd8LCqkqTWN54brxLCqpZOPIpiRebDfs4fSfWLgSNw3c0GWBLJJVTwQha9jKkG4OY74tMrOAIdm3JJOAOq+40yUc7GBU2MKJToKwz+Ai5TlIUy99
      SOME_SECRET2: AgBjuOSjgWD2wibglhZQpYFc4o3M8lGhl4cN9zwfT11Jc3FH7JkMG48hCv2EAvLrRT9G5PBgHewYszuXFWvEZFbLcikAtIaAqIE+Cm5zJDpxHC3EYb72dBPWoGH7k22gf1n9MTUJHsSY02rwoDKJwE7yb/qowqd0GLhtLa/cv67K7x8C6CPe7hTW6rT20FNCvVv4I7/8q17Q3wm9DipezqrzygmYKzZkzkHlATLwKuWvzCt+l8Fx7Q2haj4qoDPKAr/0ez3jOEKAiTczeR3CSz52JOdPI6i+eNtGyZ2/75V/8nK8fcckp1lYNByQ5fb7dFssk49g0hqLBbt4kzXqE6T4ygQpVgkPbz67lZxQMjgd7TuQ2PuO1YkNBqHg8j+/V/f4xU475tCFofjNfbY7C7t6DJ+2jZWvkO2KNP0rYb6cF0Qpu+CqgJNVmKfmHhNIcoWZKmHEk6JD+c92byBoWlWSYv0y/nGkd98SlSXh8lq42hWoyAa6YKk6eTB5K/RpJ4qYYULcZ7/ZqwQjiW/zOjS2bdTLZ2gFNjy9+uYrMB3dg6HyhvI/zRKuLYBBrjGKSWewjac+wV69QKJlYqUgGs5B6ugis8QQLQJD7I2CQFcuinuSKaNUblq7X31nG4UUkYwlpEmqJWK5hALqG0FseuI+H90ZxwfqxfK4B6FZuoloMslotLqLlgbjBOo5ICmaI7J+RFkdilKJJg==
    name: database-envs
    runsOnList:
      - database
services:
  - name: redis-service
    port: 6379
    runsOn: redis
    targetPort: 6379
  - name: database-service
    port: 5432
    runsOn: database
    targetPort: 5432
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 8000
