env: staging
---
deployments:
  - component: cache
    containerPort: 6379
    image: redis:8-alpine
    name: redis
    runsOn: redis
  - component: database
    containerPort: 5432
    envSecretRefs:
      - database-envs
    image: postgres:18-alpine
    name: database
    runsOn: postgres
  - component: server
    containerPort: 8000
    envSecretRefs:
      - database-envs
    envVars:
      - name: DB_HOST
        value: scoredvauld-database-service
      - name: REDIS
        value: scoredvauld-redis-service
    image: ghcr.io/b-zago/scorevault/webserver:latest
    imagePullSecret: ghcr-creds
    name: web-server
    runsOn: python
routes:
  - host: scorevaultin.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
secrets:
  - data:
      SOME_SECRET1: AgBN6T486jpRvIuegD0MNAJOoNeIw/nyefG9hO44uS0TeatWJDvg0CuofxgNLCHoe9vQj7Y7gGpmoZt5WQ82oqpuco93Clk2uNy8FsGnt4Behx5Kpy4Rgk3q3GeelNaoHLbc7PHn6EQx5BbyfV6HN1HpT+r9Gs/CaprCz6zVX1McndcIyTT54u+huK9Pm+WvSBDiWy959PwVnCAGN7RlAoz0gRW/tT8BsLRM1qMCSYm8r2foa8ef0JxNE6ofLzwvGi4WG49MfM9l5x5yHq0OCXu9XkCiaRf8nfoTOBfJRgAFtGdF5+vxeDwG/e9pyYzPBSnwlpxtleXyXehQ05OVYLrwosmw9Qis+KZ7CocqOfKajzjgHwWmsBvB+UO+UwZFRAdqxiLL8nJm4CTqdRi4SnedaSrzC2UxJVsp5G9FEyie6xttTrbvV9Ou/ieKuyGUvFEtNnAWS1sUzsC8yRAOrDF7iUyV1kIA3Lx33uoWRmdYVr2ACiT3P93wauyOfjyIitygDl95uKUt02xDixuPhxo8WOFRRTQ3/oqE75jJ9jwExPeY7BbOaKDeV+PqqPZfTHxDh5+oyQf4wNleId/bthRAS1ERFsXseV+nL7YvHndFBEZq+JpITZsCEsa9MbZVtkqCvKigN16H718v2mcVUp4O8wlWGUGf2JdLz31sxL0ZHW6cod4Zm7SHJsLu8geWwxiVRxAsjnbq1bko
      SOME_SECRET2: AgAsqmGGFjAIOtAivBUsjEDrIzH0gtxxqZ7a3V9Htk1ZHXwGTAH77tBWQ4esp/IGCmHtEsN0AeXyXp+APxwm7s6R8gBxHV4IABM/jWvESietCWXw4ByMiy2WqC+hV5Igg74+JxwqNo9wDgtiaSM4v2uvLIWA0dW2aWdHxzeRmdKwxirEVRYDFIDf1KtOFia0rgRNb3/7Rw7QJY8vH6LtGoH2zeqS6PI6Mbo2IjQc8+FOQtYldTC3Oiafwsg3pPK2vfQg1JHR7cim+3EK3KBlS+5qtAlBeqlYqV5YoloyDDsrdspgGJHUcuB10Q4QNuIkuCAxeFHqaLk2EBja2zhAYudGd6xKGb4dMooss57a1TPahLIEiOV+qrJEFgO+tqHNjyIKaEG6cJc9HCGofuE4CgC9V3m7Y5CBdlRS096Ko6MqQGVrmu4SCPrk06SmqslpLbBkQJZ0obLSHpHIvjLJR6rD3LPUV2yGu06djjHVvSExbEpcWkivvrww9A376kRCkEerI+Mk5qKd7E6xXmmRm9ZmAjNiHZ7uiJluvS8nr/7JrqhUvTiALY8hBIt5M5HS6XUe8hG1BMKO6Lp2/A1Hoo3+fdh2dwrBfRMf/22oJ4Q//AVUgqo6wmXR2ugbJRFyYPuKyjA6m8/HSctVe7gSepCfaMNpoc8Z3KZFUNWLMfAgZ12zILvDwgG1H+UH69fwb9zHO8cXNL+T9Q==
    name: database-envs
    runsOnList:
      - database
      - web-server
services:
  - name: redis-service
    port: 6379
    runsOn: redis
    targetPort: 6379
  - name: database-service
    port: 5432
    runsOn: database
    targetPort: 5432
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 8000
