env: staging
---
deployments:
  - component: server
    containerPort: 8000
    envSecretRefs:
      - database-envs
    image: newapp:latest
    imagePullSecret: ghcr-creds
    name: web-server
    runsOn: python
routes:
  - host: newapp.domain.com
    name: web-server-route
    runsOn: web-server-service
secrets:
  - data:
      POSTGRES_DB: AgBulUWVqJweZIRljfijhVcKFQvV0GgXzgVt2xkrsgFfKIf84QnUGXMcHeFcDxqDKx7VZk6eo3jPPJrcCsIKTOn0qdUh2ECpb5jHz8Sp1PYtw0jeRc2GEYKau9swFBXtcLMvs0hVbmFS+S8mBgnwmg5CfiHRrtwBWisGIPX90WivUuFfYXDTcR60sul4HKDUVXys8FDxLfj/8J3L9rLLdcgKivENd7SfbcAJ3Dj/uvfeAPZyi9M53bLWBIUeHr9DLg4FXAR0KhhUvISJOBOiphSIUs13VAOOTNU1n8RgJIyHn3ssIvI9dB65l3sz2qTxOIBzGa2WMukP7QKYWR0eZVlFa/zOmAXtYrwNimIj1RCjY8yi9aOCbSuOyyT6tmDjVc4FDueEwzDHMnxM0sAck/lMDdNHIXCzpTRu0ut4c5H43JomNEXdiPn2EYE0hhaU4gKDtjhppfdSxHjNtqSPugD9sUCFsFLn4bKHnTGbu/VZFw6s2AOTjPVrRNR0EMJdKRtaPiG0HOHmg7yueW6DRAP+oTpzQQt6dTxz90+/vdUARUUSgw9BsA0Q5+JAx+brpyXC0ccd/LD+kHcpTQc9hr14WCUIeJFwIyDbGz7BgCZugeuInh9NuktfqN9Jc9gc8c/VYRE3V/SJq9SRRha5tM9tjGUx/SrexvLMJU8rkfXRElPytb1LtMhfYTWABGWF1NjGZ9YOAnTrkg==
      POSTGRES_PASSWORD: AgAZcashDBJ8Y+GxgrfUULP/xcMJVKSA//06n2/MNl0EiQhj9Dcr64lfUkACFpcgiXUEnJUYur2Lz/h5l2Yu+2dYt41IMdlI7xUyDMuutqfxL00dIKkf3Rzsw0wPqsiVxYptDh10isfWUasOr4nmxj3wMIvtpY6jcjn9QYNQUivIcHWJwPkvteJfZifAwx2YKqKgH5XczczCZdHnzNAZ0Ice5zjfoo7UtU5wFxtbEdzmkx8XPUzrNKj3Y43eHn4D9rlFU+fgRbBf1iWVy0Yui3wBqBAVSRBnjFp8hCjfc/TAJBimagaE1y4wiQPLnjqwG97OpMOjy9FffR04sjUM1CULqdXuP32kc9S6HsgRFNbN72celCu/flXQ+m5wqDoptohZEencjQsGZEjk87uZPVgqhzp4UeAwiPotnx3ERqGn0AR7cpwDlTxc0ieQyFFUJiaALsO6JsepQqcUEIXiqYV0jvk0c4yRHjDA4hRHliWjZtq6mxX4x+/6p4RJfCWBD2cQmrkWg1Dw7bWD92Dr6tNt5koHsuCx0QmV1sbV/PoZJfQ+uinFCUCwkrO1A+4iblnQ9yxBOHPA/ZKgn8HW6Apydow5+0guCdHMIuvEqNsnxLsSRB0QMqanWOezjag48ixDYyphH7WVtRmGkiw89RaHBu25Md0uBqsVNMmAreMtjLF286aXqCO+fSpEdSjozn3Dd06kvtOEOQ==
      POSTGRES_USER: AgCHBKZJ1Qr2eHLmuh4q/x10PGKYKXsq3RZybRJnz5PXEZUNpu56aWvSqUTcJkWdNGVgWtDE1z+vwXeTTCR7h+23YE5zmi3npSyaLaZ6JRNL6Tj60sCkkZZJV6PCMeXEq6Ic08e+ofl++QthEBzAd649O1FU43ydWBRv7cxBVCYmpljPyWQA2Ws5s89U4DXfGhakmuVx8dOcL6y8u9lIGC/86XQKY9qVwL22/A3oWI9cv7xxMHfkzDNY3F8NWGLB3VKD2QiMS1Twsq2zky1raCMft5DCtvK9OFWLw/fZFvbx/PXHe0888a/SmfllW97ZbD9MK65xJ0u/KRuYPI8abOs4T64Dg4hkpH48IEP8+OovlOcmnefakQSMyK+AFAZ/B8r9rLU0HMwIiF25rFHorniJxHPk5OFsYehYCRX+BOEicsZ/2B65n7+ECfTcguq78yEGinyuZSigT+gVuI5f2yuUZxsZz/s9GvNb5MaT2JsKPH2FQUeL76E5rlIv/MVgjSEzaE6RgOo2Rs2GJ3acnTIiZsP+8GyBz4Cq9qCP6mUz2rJ2cKvOkQ620/xXRDn/WTIjKUm7h1vHkcNpeZx1SSFTAMGa5DNFivwrRe6Rrq/wuVHjce7pxql3It7eyxf/QWZoJjhHqX/CqOh2bj+GlABQYxvUTj6zpLqJh8xc77x0aucihUXQCvMxC6AZ90j0jbXKvTZMVagL9g==
    name: database-envs
    runsOnList:
      - database
      - web-server
services:
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 8000
  - name: database-service
    port: 5432
    runsOn: database
    targetPort: 5432
statefulsets:
  - component: database
    containerPort: 5432
    envSecretRefs:
      - database-envs
    image: postgres:18-alpine
    mountPath: /var/lib/postgresql
    name: database
    runsOn: postgres
    storage: 1Gi
