env: prod
---
deployments:
  - component: server
    containerPort: 8000
    envSecretRefs:
      - database-envs
    image: newapp:latest
    imagePullSecret: ghcr-creds
    name: web-server
    runsOn: python
routes:
  - host: newapp.domain.com
    name: web-server-route
    runsOn: web-server-service
secrets:
  - data:
      POSTGRES_DB: AgBynWI6C/+QS/7PJxSe3EkStiCI+lheCevkBJwD2F84yAGIQg7j55MqI2Mi4EovQhCWAMgfStscM8RqbWNlSu5YJXtbUXkgqiuke44zbE0eQWEzThabN+hkqqsk1XfTv1dSdZ4TxBPnYhWB/L+sQ15iK7ZmkZNfl8fuQfnzosbD7k0ovmgZk1zJrkGmPw0N1uaTFQxKOHxh9ETQIVgziyu6J+8plpaY5H9fyqUgFfkYmGx4ffQEEoFAtOx+Bwp5hOzVEH2uUGnVl+uR8H6sNidL7knKb4rNUiqM5ffFqH8Z2SnYl5qDXh5v4GNO45qNnksBOcck1PyPDoQUEaOtZMPdWsM5tBslbEEmP41B2rPb33k4FWIcobKnh6rhkgkSDn8PvK5Kf2YJwjxG+j5gX+aA/ue7N9/+2JFy1b78oxGheDOeNwGXLBCTHhxdmo3neaBAZxZnlsSGcFZPrY6pLG/GmG71i4bEcZVwHDRLRyuPSYvihc1r6MT1JR5su9/psqY/Chj1tFfL9dcosUB5oNB3qy86IijSt+82vFDHsLPnvzULuQ5XjtPt2MkgX0GCrIdijP8TCaJ+S7/qAV9f+6OgRT0X5e9Y2561RE7r24pXLg1F/MtXkEfnmM1xy9JYneoQUPbBS4ceVaeCTETAvcNTevnhw31DvTDQ1rvN8/0GXCSy8Cm1/YHgkKjM4UatToBZA7CjWxHtdg==
      POSTGRES_PASSWORD: AgAmiGiunBOuLArXqAIltHrJBAqnCbLa9WgK+czswhRg3KN2Co9aFpLz++hKYrJQLGaUASF9EGzwDJhKsIk/5GtdK9Bn1MbWbVKvi30wAnX3iB6KOWVnMlhitXjod93wmjN+4bCQGAqWN5rX8ah4/y3JOt6UtBW4F4p7/u1t+RJAEreaCPBIp2EweksHHhKgOq47wG3VQBvRDXMj+6jKcdJqSYyjIeICJQsmyRit1R4hBboEJXamlWHxoL1A5bGrWyFSwSusZXj5b94VDRp/xSmzmVsYpzZCm1SDfktuIcMkv1zyuEsDWhWr3h+I3O/fKoNVHjUYnrjOeHvV3hRGi+0ZLOM2RHlChEQK3K+o72pBXUL+0kGpavoFdY3pZHJDriJLoS+Rv44FYkxP4iSbxbfcgru20WZm9XOtdzhOHgMmFE+2JQYNUqLLtJV6VZhLZTEJYZzj1EQB4tQ3tiCo2dZFC980shPaMQ84ELlNyfRc7vjYeXLlBti9eH5T2loK47QodE1DGf/Imu+iTNJxHyIm7G29m60IZadpSdaSb14uVEHgJ83H2XlKJDOYM7Ja6jVUG66oE/q2MkUGUu2c91/lW1tBqQBfovs6DiM8AY7p2wh+4H/TM0NR6a0v/gekR9/a1aotwkr3b+nwdV68EQSgRm6j/WTrZ4GDtgGLAWn8pNLLoVmJjscEzsqi0wzN//kaqvSOpnX6nw==
      POSTGRES_USER: AgBFEkK6sz701/I9lyrQOoA0iAaC4mr0c6BjD9Ufk5kYpyH4M0w6BNCkkXdQSvfmZWvXCQBa4kZn3wz7QGvuQfHh0PPS1xflJNfA0CkWq1bFOsk+7d5L5mSwZYokEdrlQAXEsi6aPwlPJ//OkllqZi41zyvDDunhloIh/3FSHSH45eKpKB8QnC1YDJx1faZSIOjHwVAsQW2FPV9ejIeU1BbXrNYhG9f/o0F0j/taXKQruCSm/iI9Q9hmvoO2acsqbrll7GPkbxs+2XD8J3DbZ0YxYkm0QjZqE6qhOobjt/I6gC7RpFoCbad549ufpV+qrhQO9vNSZJdYKIpFwkk4GuQu8D2wbJhxZPajyvGPdP9m/lG/7Zza7dT3xCXfqn6VBSLKA321+EU+U03aQogURT3kHgzo7tk87ubtyHCnUOmEBu1vCJeJxkqzV2VW4ZCY7Krfdzvu6RwaLj/B0YGYEUYRbpq5Q9qOpUDulCsSlRjfrDrqiYfaK3NOwa0N2ZDWXhezwN/3yzMJVh01FwKVsck9T8lSTXIFU4HpouyD9uUMbkp9N6osCSW8s/mhn34R+Dpn1p3Z6dlXkK6Gu4e8cd08dedoOs1p3kZ+amNI6cTyOa0eEBO/e88K0TzSRyWkv5ZzpCtyRRs7W4MfQeFRIUiCA3sSa83XidAzVU6De/kozzMvqDj5QC9hIRj+swhp21xca0ujorvO/w==
    name: database-envs
    runsOnList:
      - database
      - web-server
services:
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 8000
  - name: database-service
    port: 5432
    runsOn: database
    targetPort: 5432
statefulsets:
  - component: database
    containerPort: 5432
    envSecretRefs:
      - database-envs
    image: postgres:18-alpine
    mountPath: /var/lib/postgresql
    name: database
    runsOn: postgres
    storage: 1Gi
