env: staging
deployments:
  - component: server
    containerPort: 8000
    envSecretRefs:
      - database-envs
    image: newapp:latest
    imagePullSecret: ghcr-creds
    name: web-server
    runsOn: python
routes:
  - host: newapp-staging.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
secrets:
  - data:
      POSTGRES_DB: AgB5OAEXmwe3MPVXY9CLM/nJS3hVtyAkAjybW40nNw4xw3BUSnwbisRdwto3V3ZWV1neY54gRhqKc03FGLreT4jArFe2r+/yL3V4QsCeZggkVGJIYo9aGZY0nWHu6hJCC5uwLvsvDJ7avNb3/7h6fwAaPHKYsNXlf4Tn6EiVbpqDZq8eOdOxOK/yd1qq+J0J4ynOJqOMPRsjMcNyEFN4h/0BvZl8oTsJTClS6LFbXwILLwdqJEQ1kmomLxV2vLQaLIi88Pdpje8t6JN73KkGeIdgsgkgWYO/Bek+t4cEIJX/57OnejisXUM1tZPw/pgmvEug8ukhlY6sgh3+Unyf/i6FWj/CvWFfNLv35eT+Z7JJux/jHwb4jUKRxacr8QwYYBUTndwLyu8om6wnYNGlUeOMfYziNPmxFhbAgGFCYvFZMQgvWI0YqhPQ79P4nd+A/ByfbO/5aABtGjrdZ05l3CEtce5PfuanhfqOa3u0R+t7ftcI1tMz6guDzWJz/889qURT49QKMoIAKlgEcv8SvuNtFeXsXI1/tGXvFjm9WJDMPUB705cFd8rGyCiNqKjfT/5DNtvR8oLQbkLLHF8tq5biT+rn+I6l0BOLbcGGUPLTZ4eZT9pmmgMuC5X0QD2x8bTq0SBpVZ6qCTnKwYL4cM4tBkfNEvVlE+oDusQ6ecNXfVuMzVIOnebWl402kWqsECaZmj39R4mwnat56kkurKTC
      POSTGRES_PASSWORD: AgA73e06wWRzlgyMWIQsx89/bqGgoUrm0knj+R91VffJYqXj3gcw/ariNHa1e/vjRLbxF7jxNeBZfW7ZSN+EBYruJbAIAsCOQfAi+oeO7JKm0Rn4YLU2DAJ6DnP6Pwx0t0JlUmck6beCVnzTetekXF6FJGc1dacjJuvu3zxFYULXrC8tOTU2Tuv9KFUHGxggFnslvIstEzKvyNJTprBI4ds98AFWBVhC5+/PdxFtmcRFaorN0w4PXgIAin7PCZUR+Xdd54TE6nDr6I6A5E2XZkLK7HyJrIk2cf5leOTFSqJR6gDdhBeZ9O1ZoGN/mDigB8dNIg6GxM9anqzICGJULGMrIcscsO94D6QjdeOtOOHka6hkgOYi3F62d10zfqq47Rb2eAUMdKHeXmueea+cqw8IcRIcEXpowWgn2+VUNRyMhS00UkIIdEFG6PYNqwPIE5HIMylkCPhlObWTc7uvh3DhLJMCnXfXCOPX5BH0CI24U56A06vGoywzYdTMP5YWmGfoJGI9hrogx48dBbRzdrnsPaJ1jfiwxhnRA7DFo0E3yymanhVCj1p3gTytZOD88nULZf/JKCKGPx1qED20M4cYEvojrbvHoCgob2dUgYaV/Je84KoOE3tQmGvTJDlwGlbvheT+bOPjKJFIeJZt4wISwq5M3DdcLgofMpQ85k23rDJgHVyW6vkyoR1vr36un/1unF9idFMF1o1fAtl+TBHp
      POSTGRES_USER: AgC5Okh20LS1EXE/KUlQdHYgB9tPVOmfIRZpWopSIuUN2I8z6DqP+iOuQv7Pb0DwA4o6XRNYF8//QGGugH4VPfwkfTuPocqlh+qGtQxNncwOuE5KeeqhndShIrvyIOkB8WVzmtmkWFa3+1V6QFChKyDaQV2F1hwNt589k2vpeGIb5Dw5Z8o1ydyGXq8mKoSU7HFkg0I87Q7wUoIH7s89drjr1Q1RQ4uSdP+TUuHhOtghPnosfuS/CNU5cRWZyI46tyeqxfMRyV3BorzzYrMGrNreI4En/p72KdaH7MTrXBp+ax6CqqBZRTjYsHqzpYxlL50RYrMzWi2NkQRZOtolkmyNsdOedf3izXcIxx6A0ZfSyZAx4fZ4XMYNXFIKtHRHFNfRgvt3hSemCvxa26UF8FwH71Ee4xyC19SSsNbX0ob0nUY8HKqlWnCJjZELGyzmGMWygWCYrQx4gIelef7x2AvV1CoJSfLKUc96h8NdPUI40pIhKwWanwWzUr0TbQ/1Um1IqZypEATTQchNcNHfyiqFV1nxKXdJAtu1RDpNAHc//FwRtf7aO3wmT+keXp18YnuHsMd3U6eiI/PwBQAvpLLkp/bx9zY2srgzd0HK1MjQ29LqiwDe1m906vAswHaR9oN88TyJXTI6FFkOcP+AVeMfrD5wqCJc4BoWuE1eyaQYFuiAFWEP2QvEFuCx7QioEafnZFywdynbAwHgbKt9lsIf
    name: database-envs
    runsOnList:
      - database
      - web-server
services:
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 8000
  - clusterIP: None
    name: database-service
    port: 5432
    runsOn: database
    targetPort: 5432
statefulsets:
  - component: database
    containerPort: 5432
    envSecretRefs:
      - database-envs
    image: postgres:18-alpine
    imagePullSecret: ghcr-creds
    mountPath: /var/lib/postgresql
    name: database
    runsOn: postgres
    storage: 1Gi
