env: prod
deployments:
  - component: server
    containerPort: 8000
    envSecretRefs:
      - database-envs
    image: newapp:latest
    imagePullSecret: ghcr-creds
    name: web-server
    runsOn: python
routes:
  - host: newapp.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
secrets:
  - data:
      POSTGRES_DB: AgBrRIUdAfK04JEAxnRANEaj2TJ0jIxqhmk5UQy5w8Xi1vMa88eUbwN1PoyCN8cGcmmtwNOG1zZpURL72XywDq07Pf/aF21dB8quMmoQnW05DdRz5a099mX/KUX/Gmg8EThzwq5Q+DUCmyALc47qsFU5tYpTBQCW0IsLEgaWlp72YIK3K9mePHzlcy5E61kAtRWaKPuLkO93XHpRlTOCCinOGisiv0QhS+UpelIiZffHoKamkDgo7F13aJ7eAkrnHcgVrAF8J93ho/DI/kEGpk4OE0TOBuGx2xcs2vZDE+rlv5JXJZPXaAJq8XvV9FwrDB7LCJJW6Moipdqq7NzfOVBsSv2oeuLHy4n9lhzsJqmvUffUxY7Qyqpg/A/DQ0vz12DurFfE2EGSXBdtF3SOMZqXgX6O+uyuIfIn3TuH5IDbc2KVMlj3HkeGNygtVYTKT36dZnjrgDiQ4RjYUI+JZaB7iW2dOQib/fn2Qma33f3m/bgs/rilIPcfmAlgEAloAozp7tGAQzpdiGwxCcqTB9lVpzP/61IlA48v9YL6I7BFHtB957Tr0KuRe1KBgnz50xNW3XdlnEMxDXJgfl3XU1/uIu2fRvi6QUYWLPy0VcK5wbSec2gLPUtiiTKiL3qGkmf8fLKowE+ZLpaMSRGFHQ4wVgMBoW8tlCn+uEowr6TcQNNePNy1FwBKBvayou9P2X8YkLdVYl1D8m8LcNVU9zhs
      POSTGRES_PASSWORD: AgDpk+k5m+t1tIPPnE9ZOddzMySrp+kcH7THyu9OY8LspoCBuEaGg85jNlbkHG0dvbWu0UV5u0amuohQ9DGieW0t1JFfxqnmtSlpUlgZYll88yEJFPOUiFaSjyMA2HC8fMeXxztIRoKKj/Xj2m539SvPwhiVYvJOEd7UFgzkconD4TEQUBSwyatTPAFnaNhShF/J/5cKJjcLzbrcCvb/ztVnNTtVCmiMD0cEevH7Es6HjWRY5obKJfZfpv6TxB6PMR1yfDpGdadLPsjV7XIs2PJfEXVYAW0uNtqwM8zDN1EfyHwiyKFfYotWlwRlpSgqmAgRhjCf3lYsWCYzGeDf/I4J1OubJmTplhjnSKGvYZ0nF4ZJ69rwa66lX48fusRAx25RMJELV00MH1NcKnTXxH/jvQkBSjstzwMlgRhb/z/9Upiej1avYHMK+jX7Q1PDp/SiLqJldHa5Quu1XnxmxAfkSqVAE9iuDldxB7nlh/sfNc2gS899KJAMa0xM5Iu+XvP7S3EuneaF5sdb/NS7y9Ymp4PX5pmlGAPX7ri+4BCwu9fHg6BOxYTyUKzdDOqQSnUx62vwCvd+pmkuP9mAWIlyrPvUxPeVqBhIaDC8c0dyTJBnvVzOf7CHZ7KbTtbpedAxHhQuOUEpJDvei7jHtWPC/xgeVi3PSGK9G/2RiWZBHbHmzNATt+sEzSuxb3gltGBK/8FUT8dI8xVesIsN8auk
      POSTGRES_USER: AgB8tzYwkrwQ6oMOc0s1PPVx7OcMgQpPpJd7uyDcNcbvnsbUh7cmcOrbfIuvbK5TicQyJO4GP5edbE3HaDRrNN03y+5ZESavSNa9NLOE4N3jRX88wfeXRm9X3kwT78Nsag0IzdaQSQy8wbZLJ9PX4N2H77Z+shXahbrVKGJi8MCy/roUxNtzy8VBySV0urupeShfeBF4RYIk8InPud65I151AKwqOJU0kMu+YbMb+CLV60kRPLlDOeCtdUI3uAE5gnWh/FQkjaJPLAZlSFoJUMMJlXlvmr1qR4wUligCeepAzdIlphr73R4FYNR+wi2GUpKs8/brx9izruk0yBGHI3ISAOVF77hrGhl99IyW1llDkf7iDjvARKMGoSfKMuYpigGQ+BE5BtTTvjvPFtGYa8jKNW5XKYMHM/C0VC+M+QPV/ZfT1QxWFprLfsTwNa/C9LZ+SRzmBic4TpLUw1m63Inrx11vsM/24ITndLX2+VJP2JPxt441ngNUw359Iu8talAA+8vp8F+AOS0qYTpoiVSluzuzLxDb6g1l4QACThvGvV0PxhwJ4sM5T4HjQO25i8MtVJ2MSMFW9c4J1F2uJlYUSN8Wz7+mjnoDcfgRcCPSp/oO1sf8FLm70cU0nEnwQfj5fyfcfZIMVY9MFuePfxVMjFnNvI9j/9/J6IMpR+iLQrmJXbrH6H1XB7z7M8WwET8Cw/bv49npqOd1KwrixJ6F
    name: database-envs
    runsOnList:
      - database
      - web-server
services:
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 8000
  - clusterIP: None
    name: database-service
    port: 5432
    runsOn: database
    targetPort: 5432
statefulsets:
  - component: database
    containerPort: 5432
    envSecretRefs:
      - database-envs
    image: postgres:18-alpine
    imagePullSecret: ghcr-creds
    mountPath: /var/lib/postgresql
    name: database
    runsOn: postgres
    storage: 1Gi
