deps:
  - services
  - secrets
  - deployments
  - routes
env: staging
---
deployments:
  - component: database
    containerPort: 5432
    envSecretRefs:
      - database-envs
    image: postgres:18-alpine
    name: database
    runsOn: postgres
  - component: server
    containerPort: 8000
    envSecretRefs:
      - database-envs
    envVars:
      - name: DB_HOST
        value: score-database-service
      - name: REDIS
        value: score-redis-service
    image: ghcr.io/b-zago/scorevault/webserver:latest
    imagePullSecret: ghcr-creds
    name: web-server
    runsOn: python
  - component: cache
    containerPort: 6379
    image: redis:8-alpine
    name: redis
    runsOn: redis
routes:
  - host: scorevaultin.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
secrets:
  - data:
      SOME_SECRET1: AgB8jYSwKNp5XORq4gqgvtupYgxn+BhPoQ9j28qSUs1jk0B9vcZkTa9iJYpYI7Kwf6RHs/rCwE6OuZMi2OsypXBTt0JG99ctxsX/Si8nFwHvjN5zpQHYyFJYIFNDqLv734ID2JNT/BhiOBHM5WfvDe3wOKpN6BLBdOroQ6WmMq9x5wGxlP7pXZb9+OXGFPwyOIbVzD2rtTv5lPrIZ8ydDjkpQL/rLVyBYNW89LLNAkiNDnrxgncLh6/PUT1xO5TEnpp2supxDwVCXPtT1olgnLiU59JLXV3mME7URdFNhsDf2dii5oSpUfm+8akqvJsHxm7uBRLVJ7d0qTbcJCxI+/g/dcoWqkaYZ8418i1w/IBmr8A08cFfYASw7muQh6dHFaEQtK5/BsD24x1zZCWWURbGL/ZGoazz95bSujKSE1LcDlfDItOo+dOh5ZF7NO5xKZyryv4zrbeQSsGetYknpSqPiJKahGwHN3zjABV+K0rQ0aSASX+GQxgcYvJk7SK9fTUg0pmVAJe4grcQhcuPrpoNowPyCs6ne0vW4b96VMMIkd7EPBwqb4ddccurmeGd1SbR0D5eG/z6cj6Jux801L7nFiE2ksOKdLqlNuWjHlyXul23o2h6ZmghNihMut6zfOZd5bJPoSfYD0vIncG+fyJNI6w6/mVLzi7DQnrilpezDDnfSDNyDGZYKba0oUNyIlzpuL3E1ajbv4jF
      SOME_SECRET2: AgBBOtE4L5ngu3yec/wqja9Kww6UO8Jz0t44tWi/EMmC30kONibuNZ7tbvQu8NT4kkxMAF5Rsh4+bUR/8VuXdUuECQ9U/kFchcu6MlZcFgDJnoFacALqPGqjdoKhLlbhnQ95rbdlOYqu6bXsN8OF+THMXbEDq+SwgNOPclP8Wc6AfTAE4vVyPbPbnQejxK+JkV1BnyoKdB+RQjKAb4J1YHT83ubypL+fwKbhqYaBMsEqfiKnBdI+A85Lx7FV/+LD+sYlwoBRVtCyAE/6ukMrOO3BGUblT2oCsYpWpctvUdwDu1vz1xIROJUzyYu7qabEcNMXXQo2RfngWEhYeacXW2dFo0NbUzOxsPrywv8tSotCLpTBS7IeQ+849l8KFqGCNpd6JJT+vZ/NBctifN4UP2JFrthabesTA1wQuwVYHvHqU+xI646ncwx6mHI2R2W6d8axqErG2wehl1Av/kOxr8b7an+/NVyJLLFt+dJ9JfSU3OcwkjYAbIGVDoA12OQVBiC210wgauwl7uKmj+s638i+5TG6j8uf/+0iCrFPpIj4oKXb3oh1+s0XJYk/SCZ38XU9pBLOGeplBpJ7VRSZxYOB1fbIO9iN4fpT3Dp7QK0qEIpweAHdLvRkpG8tgHw6wJplQh9nC0Rmtky55ebEzJUjzHTB9J1Ko/Q3a8yNjkm9NK+5tkMKiggWVEGqDDY70mKtfoM9e5gu4g==
    name: database-envs
    runsOnList:
      - database
      - web-server
services:
  - name: database-service
    port: 5432
    runsOn: database
    targetPort: 5432
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 8000
  - name: redis-service
    port: 6379
    runsOn: redis
    targetPort: 6379
