env: staging
deployments:
  - component: server
    containerPort: 8000
    image: app:latest
    imagePullSecret: ghcr-creds
    name: web-server
    runsOn: python
routes:
  - host: app-staging.zagoapps.com
    name: web-server-route
    runsOn: web-server-service
services:
  - name: web-server-service
    port: 80
    runsOn: web-server
    targetPort: 8000
